### ISSUE TITLE
URL parameter encoding differs depending on notation ({param} vs :param)

### ISSUE THREAD

**Issue by gr2m** [octokit/endpoint.js#207]
Example

```js
const { url: url1 } = endpoint("GET /repos/{owner}/{repo}/contents/{path}", {
  owner: "owner",
  repo: "repo",
  path: "path/to/file.txt"
});
const { url: url2 } = endpoint("GET /repos/:owner/:repo/contents/:path", {
  owner: "owner",
  repo: "repo",
  path: "path/to/file.txt"
});
```

- `url1` is https://api.github.com/repos/owner/repo/contents/path%2Fto%2Ffile.txt
- `url2` is https://api.github.com/repos/owner/repo/contents/path/to/file.txt

`url1` is correct.

I'd appreciate a pull request if anyone would like to work on this. You can start out by creating a pull request with a failing test reproducing the above behavior. The test will go into [test/endpoint.test.ts](https://github.com/octokit/endpoint.js/blob/master/test/endpoint.test.ts).

**Comment by romanbalayan** [comment]
Hi @gr2m 

I'm currently participating in the hacktoberfest event organized by Digital Ocean, hopefully it won't be too much of a bother for you to add the hacktoberfest-accepted label to this PR so it may be counted towards my progress.

Thank you!

**Comment by gr2m** [comment]
resolved via https://github.com/octokit/endpoint.js/pull/210
