### ISSUE TITLE
[BUG]: data-time range parameters do not seem to be working correctly

### ISSUE THREAD

**Issue by doowb** [octokit/endpoint.js#497]
### What happened?

I'm using `@octokit/core` to list workflow runs based on [the REST API docs](https://docs.github.com/en/rest/actions/workflow-runs?apiVersion=2022-11-28#list-workflow-runs-for-a-repository). I'm attempting to use the `created` parameter with a date-time formatted as `2024-07-24T17:00:00Z`, but I don't get any results back. When I only use the date `2024-07-24`, I get the correct results back, so I'm not sure if there is a bug in this library (when encoding the parameter), the actual github api, or if the docs need to be updated to specify that only the date portion of the date-time range is available.

### Versions

Octokit: v6.1.2
Node.js: v20.15.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by wolfy1339** [comment]
That would be a bug with GitHub itself. We don't parse values given as parameters

**Comment by doowb** [comment]
Thanks for getting back to me so fast!

Do you know where I can open a bug report for the GitHub API?

**Comment by kfcampbell** [comment]
IIRC in the past we've pointed people to [Community discussions](https://github.com/orgs/community/discussions/categories/api-and-webhooks) for these types of issues.
